### ISSUE TITLE
Changing of password/passphrase

### ISSUE THREAD

**Issue by javvylx** [jlund/streisand-discussions#102]
Are there options  to change the default login password and VPN passphrase and password?

**Comment by cpu** [comment]
> Are there options to change the default login password and VPN passphrase and password?

Not presently. Your best bet is to destroy the existing Streisand instance and create a new one to get fresh credentials. If you're looking to set the password to one of your own choosing, that isn't supported unfortunately.

You could achieve this manually by editing the correct files on-system and reloading the required services but I'm afraid your best bet is to search for help doing this on a more general purpose Ubuntu server forum. You would be into the realm of doing your own system administration and not running Streisand anymore :-)

Thanks for the question/issue. I'm going to close this for now since I think your question was addressed.
