### ISSUE TITLE
OpenConnect on port 443?

### ISSUE THREAD

**Issue by ghost** [jlund/streisand-discussions#111]
Hey there, I'd like to know how I can update my Streisand server's settings so that I can be able to connect to it via OpenConnect using port 443 instead of the default port provided (4443).

Thanks in advance!

**Comment by alimakki** [comment]
Hi @FFEC 

Since streisand already multiplexes connections on port 443 using sslh (for ssh, openvpn and https traffic), this unfortunately isn't possible as OpenConnect is based on standard tls for authentication - the client will end up hitting the nginx gateway instead of the vpn server and fail to connect using the standard streisand setup.

If you are on the other hand willing to sacrifice the gateway this could be possible.
The steps you would have to carry out (off the top of my head) would be somewhere on the lines of:

1. Stop and disable the nginx gateway
2. Open UDP port 443 with ufw
3. Edit `/etc/sslh.cfg` to something like (redirect tls connections to port 4443):

```
verbose: false;
foreground: true;
timeout: 5;
user: "sslh";
pidfile: "/var/run/sslh/sslh.pid";

listen:
(
    # replace with your server IP
    { host: "1.2.3.4"; port: "443"; }
);

protocols:
(
     { name: "ssh";     host: "127.0.0.1"; port: "22";     probe: "builtin"; fork: true; },
     { name: "tls";     host: "127.0.0.1"; port: "4443";    probe: "builtin"; },
     { name: "openvpn"; host: "127.0.0.1"; port: "636"; probe: "builtin"; },
     { name: "anyprot"; host: "127.0.0.1"; port: "4443";   probe: "builtin"; }
);

on-timeout: "tls";
```
4. Edit `/etc/ocserv/config` and change `udp-port = 4443` to `udp-port = 443`
5. Restart sslh
6. Restart ocserv

I would recommend trying this on a test instance first as I haven't actually tried this.

I hope that helps.
