### ISSUE TITLE
should I upgrade my server

### ISSUE THREAD

**Issue by covici** [jlund/streisand-discussions#113]
Hi.  I have been using Streisand for a couple of years and I love the thing.  I am still on ubunto 14.4 and I was wondering if I should upgrade my server,  or leave it alone.  I am using a server that is in the cloud and it is working, but I was just thinking its a bit old, so I thought I'd check here.

Thanks.

**Comment by cpu** [comment]
Hi @covici,

Glad to hear Streisand has been working well for you!! 

Unfortunately Streisand doesn't support upgrading the server in place. Your best bet is to create a brand new Streisand instance using the current code in master and then transition you and your users to the new server. We're hoping to make this easier in the future.

I would recommend doing so soon. Current Streisand uses Ubuntu 16.04 which will be supported by Canonical with security updates until April 2021. The version you're using, 14.04, is only supported until April 2019 which is fast approaching.

I'm going to close this issue now since I think your question is answered. Thanks!
