### ISSUE TITLE
What do I lose when I dont install certificates?

### ISSUE THREAD

**Issue by vcozcan** [jlund/streisand-discussions#138]
Hello,

Which parts of the vpn process weakens if an user does not install certificates and connects to web interface by ignoring warnings?

**Comment by nopdotcom** [comment]
It allows a man-in-the-middle attack. Without the cert verification, you don't know which server you're connecting to. This can be particularly dangerous because an adversary can insert their own box in the middle. This is what you'd expect to happen: you connect to the Streisand server and type in your username and password:

```
Browser: username/password ---> Streisand
```

But because you don't know who you're connecting to, this can happen:

```
Browser: username/password ---> EVIL BOX: username/password ---> Streisand
```

EVIL BOX gets your username and password, so it can log into the real server, and serve as a proxy. It can read and alter all the data. Normally, you download config files from the Streisand server. But in this case, you're downloading config files from EVIL BOX, which can point you at an evil VPN server instead.

How likely is an active man-in-the-middle attack like this? It probably depends on who you are, and which networks you're connecting over.

If you'd like to experiment with Let's Encrypt, sign up for http://freedns.afraid.org/ , which allows you to create five free subdomains from their registry. Pick an older, public domain. There's a rate limit on Let's Encrypt per-domain, so you'll want to pick a less popular one. I start from [about page 100](https://freedns.afraid.org/domain/registry/?page=100&sort=5&q=) when picking. This isn't really a permanent solution, because the domain owner could (potentially) kick your domain name and substitute their own IP address. Let's Encrypt would issue a fresh certificate to them.

BTW, Amazon's Route 53 DNS hosting supports delegated zones. If you own example.com but don't want to mess with its DNS very often, you can point s.example.com at Route 53, and quickly create and delete records like poem-walk.s.example.com. This assumes it's not too hard for you to create delegations for example.com, though...

**Comment by vcozcan** [comment]
So is it just a weakness for giving away web interface password and downloading config files? It is not related to everyday use (assuming that I did not download doctored config files). I installed config files to all my devices without using certificates and installing them now would not make any difference.

Also thank you for domain tips.

**Comment by nopdotcom** [comment]
Yeah. Once everything is configured, you're fine. You'd probably use SSH to work with the server from now on anyway, and SSH has its own host key checking.
