### ISSUE TITLE
Issue with Streisand utilizing a separate VPN as it's "Public" connection

### ISSUE THREAD

**Issue by alimakki** [jlund/streisand-discussions#54]
Asked by @rjsears
> I am not sure if this is the correct place to post this, but I could not seem to locate a forum or wiki for Streisand so I am posting here. If there is a better place, please let me know.
> 
> I want to setup Streisand to connect to a VPN server for all of its internet connectivity. So I have a deployed server currently with a single network interface that is the Streisand server. I want that server to have a VPN connection to another VPN and for all clients connecting to the Streisand server to be using that VPN as their internet as opposed to the live public IP on the dedicated droplet.
> 
> I have openvpn configured on the streisand server and it works (all traffic from the server gert routed over the VPN) but none of my clients can connect to the Streisand server once the OpenVPN VPN connection goes active.
> 
> I am sure I am missing something simple (like adding another nic if necessary).

**Comment by cpu** [comment]
I'm a little bit puzzled by the use-case. Why would you want a VPN server that itself uses a VPN server as the upstream internet connection? Why not configure clients to connect directly to the VPN's upstream VPN?

This sort of advanced customization isn't something we have the resources to support. I recommend you try to solicit help on a general purpose system administration forum like [Server Fault](https://serverfault.com/).

**Comment by nopdotcom** [comment]
The use case is proxies getting detected and banned.

I could switch whole VPN servers as @cpu says. But the problem is then I need to deploy another server (cheap) and manage transition for users (can be expensive for both sides: new host, key material and certs, plus VPN reconfiguration).

**Comment by rjsears** [comment]
Another use case is very simple - I want all of my users to use XYZ VPN all of the time but do not want to manage a ton of different certificates. So I set up Streisand to be the "inbound" VPN server for all of my connections, but have it send all traffic to another VPN. 

In our case, we do a lot of outsourced work and we generally are given access to the end network via a VPN. I want all of my users to hit my Streisand server then access to end network via the VPN the server is configured to use. When the next job comes along, I make one simple change on the Streisand server and no changes to all of my other inbound connections.

@cpu I understand that you do not have the resources to support something like this, I was just asking if it was a possibility since I did not know anything about your amazing software. 

I have since figured out how to make it work exactly as I wanted  and it working just fine.

Thank You
