### ISSUE TITLE
Use ansible lookups for cloud keys and variables

### ISSUE THREAD

**Issue by chuckyz** [jlund/streisand-discussions#61]
Using aws_* as an example, the following is under `global_vars/noninteractive/amazon-site.yml`.

```
aws_access_key: ""
aws_secret_key: ""
```

This could be improved by using http://docs.ansible.com/ansible/latest/playbooks_lookups.html#the-ini-file-lookup

An example:

```
 aws_access_key: "{{ lookup('ini', 'aws_access_key_id section=default file=~/.aws/credentials') }}"
 aws_secret_key: "{{ lookup('ini', 'aws_secret_access_key section=default file=~/.aws/credentials') }}"
```

Further improvements could be made to automation using filter plugins so if a subnet/vpc are tagged with something specified no id/subnet_id would need to be provided.

**Comment by nopdotcom** [comment]
It's a real shame that Ansible can't set defaults for prompts at runtime (https://github.com/ansible/ansible/issues/11757) because I sure would like defaulting those `aws_` to variables to values out of `~/.aws`. 

Thank you for the pointer to ini file handling.

**Comment by nickolasclarke** [comment]
oh man, this would be a boon! Could this potentially also be used to handle syncing client credentials from one deployment from another? Streisand could write them to an ini that then would be stored in the generated docs folder with some in line or separate instructions as to where to place the file for a new deployment. Being able to quickly reploy and not need to update credentials would be great, especially if you couple this with a FQDN.

**Comment by nopdotcom** [comment]
You can get much of the way there with a FQDN and the ability to carry the
gateway password over from a previous deploy.

**Comment by cpu** [comment]
@chuckyz PRs welcome!

@exratione What do you think of the approach @chuckyz is suggesting? Interested in taking it on as a follow-up to the non-interactive work you did?

**Comment by exratione** [comment]
The right thing to do with AWS API use is to pull credentials from the environment. In practice less sophisticated users complain, so you have to also offer the option of overriding them.

The [Ansible EC2 module](http://docs.ansible.com/ansible/latest/ec2_module.html) claims it decides whether to check the environment variables `AWS_ACCESS_KEY_ID` and `AWS_ACCESS_KEY` if the `aws_access_key` and `aws_secret_key` parameters are not set.

The [ansible code](https://github.com/ansible/ansible/blob/c93ddf5473f7604f48d34293ca77f37ff7183f47/lib/ansible/module_utils/ec2.py#L197) suggests it will check environment variables and standard config file location in that order for any falsey value of `aws_access_key` and `aws_secret_key`, such as empty strings. I haven't actually tested this.

So I think that the only change needed here is in the documentation, inline or otherwise, to say that passing in empty values will result in the credentials set in the local environment being used.

**Comment by nopdotcom** [comment]
Should there be an early test for present-but-bad credentials?

**Comment by chuckyz** [comment]
@exratione good idea, but I thought doing it explicitly here would help those in the future (self-documenting code and whatnot).

Do GCP/Azure/DigitalOcean offer similar things?

**Comment by cpu** [comment]
I'm going to close this issue for now. If folks in-thread feel strongly about one approach vs another (or adding more safeguards) I'd encourage you to submit a PR. Happy to evaluate/review!
