### ISSUE TITLE
How to update an existing Streisand server?

### ISSUE THREAD

**Issue by damko** [jlund/streisand-discussions#64]
I'm experimenting on this #7 issue and I already have a running Streisand server.

How can I update my Streisand server (meaning adding / removing installed services) using ansible?

I've updated my inventory and added my server but when I run 

    ansible-playbook -l streisand playbooks/streisand.yml

it stops because there are some ansible variables undefined. 

> TASK [common : Generate random VPN client names] **********************************
> fatal: [streisand]: FAILED! => {"failed": true, "msg": "'vpn_clients' is undefined"}
>	to retry, use: --limit @/home/damko/vms/debops/damko--info/streisand/playbooks/streisand.retry

After a quick look at the .yml files I was tempted to start writing a update.yml file but I'm wondering if there is already a good practice for the update that I'm missing

**Comment by cpu** [comment]
> How can I update my Streisand server (meaning adding / removing installed services) using ansible?

This isn't supported right now. Everything assumes a clean server.

> I've updated my inventory and added my server but when I run
>
> ansible-playbook -l streisand playbooks/streisand.yml

There's more and more work being done in the wrapper scripts that run the playbooks. Running the playbooks bare isn't going to be trivial and isn't something we mention doing anywhere in the docs at present.

> After a quick look at the .yml files I was tempted to start writing a update.yml file but I'm wondering if there is already a good practice for the update that I'm missing

I suspect there's a lot of work that would need to be done to accomplish this and I would rather see a larger plan proposed as a multi-part issue so that we can reach a consensus on the path forward before anyone spends too much time on a PR that can't be merged :-) I would propose that if you're interested in taking this on that you start with a review of the whole project, identifyinh the places that will need updating, and then proposing a holistic approach that can be broken down into smaller steps as a new issue.

**Comment by damko** [comment]
I see the need for a wider scope. It makes sense. 

I'd gladly take this on me but I'd love some backup from someone who's been working on the project longer than me. Anyone interested?

Btw I suppose that this issue also relates a lot to https://github.com/StreisandEffect/streisand/issues/5

**Comment by nickolasclarke** [comment]
@damko although I am a project team member, I actually have fairly limited experience with ansible itself. However, I have a a fairly good understanding of the layout of the project. More importantly, I also understand the primary use cases and mission of the project. I can help sanity check an approach and get the other team members involved if that would be helpful.

**Comment by cpu** [comment]
> I'd gladly take this on me but I'd love some backup from someone who's been working on the project longer than me. Anyone interested?

Yup! Let me know how I can help :-)

**Comment by cpu** [comment]
I'm going to close this issue for now. We all agree it's something that would be nice to have. I think my next steps from above still stand:
> I would propose that if you're interested in taking this on that you start with a review of the whole project, identifying the places that will need updating, and then proposing a holistic approach that can be broken down into smaller steps as a new issue.

Thanks!

**Comment by nopdotcom** [comment]
This was referenced in https://github.com/StreisandEffect/streisand/issues/513 as well.
