### ISSUE TITLE
Load Balance using AWS Route53

### ISSUE THREAD

**Issue by hdavy2002** [jlund/streisand-discussions#72]
Love this software. I have a shadowsocks up and ready on a LightSail Server by AWS.  I want to create another instance lets say in Oregon and divert regional traffic over there. Route53 now allows you to redirect geo based traffic.  Under my dns name, I can have multiple IP's of different instances and use round robin connections to load balance.  (Not sure how that will work with socks). Or redirect based on a geo rule to single instance.

So my question is how do we load balance and scale. Can I create another instance and use the same gateway passwords in all, or create multiple instances and redirected users based on geographical locations. In the latter. I would create a single domain name , lets say myvpnsite.com and redirect global users based on their origin.  I know my userbase will be confused seeing all the IPs on their Android phone. It will be simple for them to see usa.myvpnsite.com , germany.myvpnsite.com or India.myvpnsite.com. I can achive this with single servers. I am trying to wrap my head how to load balance between multiple VPS's.

Thanks for your help and really appreciate your work. It has made life easy.

Cheers

**Comment by cpu** [comment]
Hi @hdavy2002,

Streisand has no support for using an existing configuration. E.g. both servers would be provisioned with entirely separate CA certificates, passwords, PKCS12 client profiles, etc etc etc. Load balancing between two Streisand servers won't be possible without a significant amount of manual modification & hacks.

I've indicated as much on other discussion issues you've opened but I want to emphasize again that you are taking Streisand and using it in a way that is considerably divergent from the intentions of the maintainers. We can't support/guide you with these questions because you're doing things we have never thought to do before :-) 

Unfortunately being a trail blazer means you'll have to try and support yourself with these fundamental design questions. I strongly suspect you're going to need to make significant changes to the Streisand codebase to make these use-cases possible so I encourage you to fork the project and see what you can come up with.

Thanks! I'm going to close this issue again so that its possible to keep track of outstanding threads. Folks are of course free to comment on this closed issue if they'd like.

**Comment by hdavy2002** [comment]
"Streisand has no support for using an existing configuration. E.g. both servers would be provisioned with entirely separate CA certificates, passwords, PKCS12 client profiles, etc etc etc. Load balancing between two Streisand servers won't be possible without a significant amount of manual modification & hacks"

I understand. If I am succesful I will share the details.

One way, I can think of is using a glusterfs file system with ec2 or AWS EFS mount on ec2. Once all is complete. Just create an image of ec2.

Prior to that, I will have to point mydomain.com to ec2 and when I am building streisand. I can use mydomain.com as my ip address. 

Well its fun being a trail blazer.
