### ISSUE TITLE
ShadowSocks (Streisand) --> TOR ??? 

### ISSUE THREAD

**Issue by ghost193** [jlund/streisand-discussions#76]
Hi I have successfully got Streisand up and running on a bithost VPS server. My question is, I want to be able to connect my device via shadowsocks, vpn or wireguard to the Streisand VPS server and then have all the connections tunneled from the server outbound over TOR. 

Conceptually sounds simple, but I'm not a tech guy can someone give me a bit of direction here? Thank you.

**Comment by nickolasclarke** [comment]
This is outside of the scope of what Streisand does. The server is
considered the final endpoint before entering the public internet, so there
is no configuration for routing outbound traffic through tor, or any other
vpn service. Is there a reason you cant simply connect to the tor network
directly, either via the Streisand bridge, or through the public directory
of nodes? Tor only supports TCP traffic, and from my understanding works
best when configured per app, preferably for something that supports a
SOCKS proxy, so routing "all connections" is simply not going to be
possible via TOR.

**Comment by ghost193** [comment]
Hi, thanks for the response. I understand it's outside the scope of Streisand was just hoping someone with know how could write a few lines about how I would go about this so I can have a good starting point to research it and implement it myself

**Comment by nickolasclarke** [comment]
@ghost193 I understand. I am hesitant to really give much direction because the implications of routing everything via tor in this way is a deep rabbit hole for a variety of reasons, in my opinion. However, with the understanding that you can route TCP traffic via TOR, you could use something like https://trac.torproject.org/projects/tor/wiki/doc/TransparentProxy and/or IPtables rules to route local traffic to the locally running tor bridge. 

Irrespective of the way you connect to the Streisand server (except using the tor bridge directly), the implementation to route things to tor would be the same. You may be better served by asking the tor community about how best to route local traffic.

**Comment by cpu** [comment]
I believe this question has been answered. Closing the issue - thanks!
