### ISSUE TITLE
how to add more accounts?

### ISSUE THREAD

**Issue by hadifarnoud** [jlund/streisand-discussions#81]
I have two questions
1- how can I add more accounts? streisand asks for number of accounts ber service via Ansible. what if I need to add more now? can it be done?

2- how can I add letsencrypt support? I guess my instance did not configure letsencrypt because port 80 was closed via firewall

**Comment by alimakki** [comment]
Hi @hadifarnoud 

> 1- how can I add more accounts? streisand asks for number of accounts ber service via Ansible. what if I need to add more now? can it be done?

Out of the box Streisand doesn't provide the functionality to create new clients after the initial installation. You would have to run commands manually on the server to mint new credentials.

There's an artificial limit to the number of clients that are generated, which is currently set to 20. We've put this in due to certain factors; for example WireGuard will use the generated client index as an IP offset; bumping this number to say, 1000 clients, would result in invalid IP addresses. If you want to look at the validation rules that runs prior to the execution of the main script, check it out [here](https://github.com/StreisandEffect/streisand/blob/master/playbooks/roles/validation/tasks/main.yml#L23). 

> 2- how can I add letsencrypt support? I guess my instance did not configure letsencrypt because port 80 was closed via firewall

Let's Encrypt is supported out of the box, during setup I'm sure you've encountered the prompts that ask you for your domain and email - these were for LE.

In any case, @cpu is more qualified to answer LE related questions.

**Comment by cpu** [comment]
Hi @hadifarnoud 

If you want Streisand to create additional accounts, or to retry the Let's Encrypt provisioning you will need to recreate the Streisand instance from scratch. There is no support presently for updating an existing server with new configuration or retrying only parts of the setup.

>  I guess my instance did not configure letsencrypt because port 80 was closed via firewall

Can you describe your setup more? The firewall rules that Streisand provisions includes an exception for port 80 to ensure the Let's Encrypt HTTP-01 challenge works. Did you have an additional firewall in the way?

**Comment by hadifarnoud** [comment]
thanks for the answers. I think it would be super helpful to have a command for adding new accounts. Streisand packages account setup super easy on generated docs. maybe we can have some of those abilities? or just generating the docs again?

regarding LE, I did add the domain during setup. Alibabacloud have a firewall by default in a form of `security group`. 

when I go to https://mydomain.com, I get ssl error. the certificates are still self signed for Cisco Anyconnect as well. I did not get any error during setup, I think. Isn't LE for using valid certificates instead of self-signed on everywhere? 

how can I do this manually, now that I don't have it setup.

**Comment by hadifarnoud** [comment]
thanks for the answers. I think it would be super helpful to have a command for adding new accounts. Streisand packages account setup super easy on generated docs. maybe we can have some of those abilities? or just generating the docs again?

regarding LE, I did add the domain during setup. Alibabacloud have a firewall by default in a form of `security group`. 

when I go to https://mydomain.com, I get ssl error. the certificates are still self signed for Cisco Anyconnect as well. I did not get any error during setup, I think. Isn't LE for using valid certificates instead of self-signed on everywhere? 

how can I do this manually now that I don't have it setup?

**Comment by alimakki** [comment]
Hi @hadifarnoud,

> Isn't LE for using valid certificates instead of self-signed on everywhere?

LE is only used for signing the gateway certificate.

Each VPN daemon that makes use of PKI (currently OpenConnect and OpenVPN) have their own unique set of CA, server and client certificates.

**Comment by hadifarnoud** [comment]
It can be used for OpenConnect and OpenVPN as well though, right? no more import certificates.

**Comment by cpu** [comment]
Hi again @hadifarnoud,

>  I think it would be super helpful to have a command for adding new accounts. Streisand packages account setup super easy on generated docs. maybe we can have some of those abilities? or just generating the docs again?

I agree that sounds helpful! PRs welcome :-)

> regarding LE, I did add the domain during setup. Alibabacloud have a firewall by default in a form of security group.

I recommend using a supported cloud provider instead of Albibaba. That would ensure the firewall rules are correct because Streisand can do the work required to make it so.

> when I go to https://mydomain.com, I get ssl error.

If you want Streisand to create additional accounts, or to retry the Let's Encrypt provisioning you will need to recreate the Streisand instance from scratch.

> It can be used for OpenConnect and OpenVPN as well though, right? no more import certificates.

Confirming what @alimakki said - the Let's Encrypt issue certificate is **only** used for the HTTPS Gateway website. All other VPN software is the same between a Let's Encrypt server and a non-Let's Encrypt server. You will still have a self-issued PKI for OpenConnect and OpenVPN.

Thanks for the questions - since I believe everything has been answered now I'm going to close this ticket. Hopefully in the future we can support retrying Let's Encrypt issuance after provisioning, or support adding new accounts after provisioning.

**Comment by nopdotcom** [comment]
Sophisticated users could generate say 20 certs but not publicize them, say
by editing the generated HTML. Or they can hand them out offline.

**Comment by hadifarnoud** [comment]
I'm not a sophisticated user unfortunately. I would've done a PR if I was guys :)

a command approach or adding it via web GUI, would be nice to have

**Comment by nopdotcom** [comment]
Yeah, it's probably something that could be handled when we figure out what to do with server migration; several possibilities will make it easy to do this.

Alternatively, a working Ansible `--retry` could do this. That's still a while off, I think.
